apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
    tier: upstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
      tier: upstream
  template:
    metadata:
      labels:
        app: registry
        tier: upstream
    spec:
      containers:
      - name: registry
        image: registry:latest
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: '/registry'
            name: registry-volume
      volumes:
      - name: registry-volume
        hostPath:
          path: '/data'
          type: Directory