apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
  labels:
    app: registry
    tier: upstream
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: registry
      nodePort: 31001
      port: 5000
      protocol: TCP